### ISSUE TITLE
Problems with a make install on Proxmox container

### ISSUE THREAD

**Issue by borpin** [TradeFace/gismocaster#57]
Installed onto a bare Ubuntu LXC container on Proxmox.

Cannot connect via HTTP://IP:8111. I think the listener is not setup correctly i.e. only listens on Localhost.

Stopped gismocaster service and ran
```
python3 web/manage.py runserver 0.0.0.0:8000 --noreload
```
I can now access webUI but cannot login using admin/admin.

Help!

**Comment by TradeFace** [comment]
port 8111 will be used from next version onwards. It is already set in the development branch. 
The admin account is created at installation [Makefile](https://github.com/TradeFace/gismocaster/blob/master/Makefile).
Please make sure the installation was completed without errors. ( In the currect version you will get a lot of mqtt connection attempts in the install process, that is fixed in the dev branch)

**Comment by borpin** [comment]
I do not think the `make` finished correctly.

I ran line 
https://github.com/TradeFace/gismocaster/blob/82569ae590a8ca11e66ea92f5c048e06960e687e/Makefile#L5

and can now log in.

Also edited ` nano web/mqtt/fixtures/setting.json` and added my MQTT settings

Tried running this again...

https://github.com/TradeFace/gismocaster/blob/82569ae590a8ca11e66ea92f5c048e06960e687e/Makefile#L4

and again multiple exceptions.
